# Generated by Django 2.2.2 on 2019-07-09 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, verbose_name='心情狀態')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='不願意透露身份的人', max_length=10, verbose_name='暱稱')),
                ('message', models.TextField()),
                ('del_pass', models.CharField(max_length=10, verbose_name='刪除密碼')),
                ('pub_time', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
                ('enabled', models.BooleanField(default=False, verbose_name='顯示狀態')),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Mood')),
            ],
        ),
        migrations.RemoveField(
            model_name='pmodel',
            name='maker',
        ),
        migrations.RemoveField(
            model_name='pphoto',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pmodel',
        ),
        migrations.DeleteModel(
            name='Maker',
        ),
        migrations.DeleteModel(
            name='PModel',
        ),
        migrations.DeleteModel(
            name='PPhoto',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
