# Generated by Django 2.2.2 on 2019-07-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20190709_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
