# Generated by Django 2.2.2 on 2019-07-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='NewTable',
        ),
    ]
